@hostname = localhost
@port = 3001
@host = {{hostname}}:{{port}}
@contentType = application/json
GET http://localhost:3001
###
POST http://{{host}}/user/login HTTP/1.1
Content-Type: {{contentType}}

{
    "username": "ductrong",
    "password": "123456"
}